@tus/server: refactor request validator
tus/tus-node-server pull request #402
Opened 2023-02-27 15:55 UTC by Murderlon

Closes #378

- Refactor to be less fragile and fix a bug

2023-02-27 16:13 UTC, mitjap commented
I think it is confusing to have a list of validators that in fact check for invalidity.

2023-02-27 19:06 UTC, Murderlon commented
Good point. It's only in the internal variable name though. I kept the workings the same as before, which was invalidity. Might be better yes to flip it around.

2023-02-28 11:41 UTC, mitjap commented on packages/server/src/validators/HeaderValidator.ts
> +      return Number.parseInt(value as string, 10) > 0
Also allow 0.

```suggestion
      return Number.parseInt(value as string, 10) >= 0
```

2023-02-28 11:41 UTC, mitjap commented on packages/server/src/validators/HeaderValidator.ts
> +      return Number.parseInt(value as string, 10) === 1
What about a simple string comparison?
```suggestion
      return value === '1'
```

2023-02-28 11:41 UTC, mitjap commented on packages/server/src/validators/HeaderValidator.ts
> +      return Number.parseInt(value as string, 10) > 0
I don't think `Number.parseInt` is appropriate for any validation. It parses many non-numerical inputs as valid numbers. Maybe simple regex?
```
const regex = /^[1-9][0-9]*$/
return value === '0' || regex.test(value);
```

Example of invalid input that would be parsed as valid number:
`"0100" -> 100`
`"0asd100" -> 100`
`"1asd100" -> 1`

2023-02-28 11:41 UTC, mitjap commented on packages/server/test/HeaderValidator.test.ts
> +      assert.equal(validateHeader('upload-offset', value), false)
Maybe add some more complex values that are falsely validated as number?

2023-02-28 11:43 UTC, mitjap commented
Sorry for nagging on such minor refactor :)

2023-02-28 12:06 UTC, Murderlon commented
> Sorry for nagging on such minor refactor :)

Not all all! I went too quick about this refactor, not thinking enough about potential other improvements.

2023-03-01 09:17 UTC, mitjap requested changes

2023-03-01 09:17 UTC, mitjap commented on packages/server/src/validators/HeaderValidator.ts
> +      return n !== Infinity && String(n) === value && n >= 0
I think this version also parses non-integer values.

2023-03-01 09:17 UTC, mitjap commented on packages/server/test/HeaderValidator.test.ts
> +    it('should invalidate a number < 1', (done) => {
```suggestion
    it('should invalidate a number < 0', (done) => {
```

2023-03-01 09:17 UTC, mitjap commented on packages/server/test/HeaderValidator.test.ts
> +      assert.equal(validateHeader('upload-defer-length', '-1'), false)
Added some more tests that might fail if `Number.parseInt(value) === 1` is used.

```suggestion
      assert.equal(validateHeader('upload-defer-length', '-1'), false)
      assert.equal(validateHeader('upload-defer-length', '+1'), false)
      assert.equal(validateHeader('upload-defer-length', ' 1 '), false) // test leading and trailing whitespaces
```

2023-03-01 09:17 UTC, mitjap commented on packages/server/test/HeaderValidator.test.ts
> +      assert.equal(validateHeader('upload-length', '1asd100'), false)
```suggestion
      assert.equal(validateHeader('upload-length', '1asd100'), false)
      assert.equal(validateHeader('upload-length', '1.3'), false)
      assert.equal(validateHeader('upload-length', '-0'), false)
      assert.equal(validateHeader('upload-length', '+0'), false)
      assert.equal(validateHeader('upload-length', 'NaN'), false)
      assert.equal(validateHeader('upload-length', '+Infinity'), false)
```

2023-03-01 10:33 UTC, mitjap approved these changes

2023-03-01 10:55 UTC, merged